FROM php:8.1-fpm

# Install system dependencies
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip

## install xdebug
# RUN pecl install xdebug \
#     && docker-php-ext-enable xdebug

# install node v16
RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash
RUN apt-get install -y nodejs

# Install PHP extensions
RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd

# Install PHPRedis
RUN pecl install -o -f redis \
    &&  rm -rf /tmp/pear \
    &&  docker-php-ext-enable redis

# #install PHPSwoole
# RUN pecl install -o -f swoole \
#     &&  rm -rf /tmp/pear \
#     &&  docker-php-ext-enable swoole

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Set working directoryls -
WORKDIR /var/www/html

# Add user for laravel application
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Change current user to www
USER www

# EXPOSE 8000

# CMD ["php", "artisan", "octane:start", "--host=host.docker.internal"]